import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync(new URL('../src/views/VideoStudio.vue', import.meta.url), 'utf8')
assert.match(source, /MiniMax H3/)
assert.match(source, /LTX 2\.3/)
assert.match(source, /selectedVideoModel/)
assert.match(source, /buildStudioCanvas/)
assert.match(source, /createProject/)
assert.match(source, /updateProject/)
assert.match(source, /router\.push\(`\/canvas\//)
assert.doesNotMatch(source, /工作流已准备/)
assert.match(source, /novelText/)
assert.match(source, /handleNovelFile/)
assert.match(source, /accept="\.txt,\.md,\.docx"/)
assert.match(source, /粘贴小说正文/)
assert.match(source, /生成故事板/)
assert.match(source, /clearNovelDraft/)
assert.match(source, /parsedDocument\.value = null[\s\S]*novelText\.value = ''[\s\S]*storyboard\.value = null/)
assert.match(source, /parsedDocument\.value\?\.text !== novelText\.value/)
assert.match(source, /@new-job="clearNovelDraft"/)
assert.match(source, /novelFileKey/)
assert.doesNotMatch(source, /if \(!planned\) clearNovelDraft\(\)/)
console.log('videoStudioWiring.test.mjs passed')
